const category = [
  "Electronics",
  "Clothing",
  "Home & Kitchen",
  "Books",
  "Beauty & Personal Care",
  "Health & Household",
  "Toys & Games",
  "Sports & Outdoors",
  "Tools & Home Improvement",
  "Automotive",
  "Baby",
  "Pet Supplies",
  "Office Products",
  "Grocery & Gourmet Food",
  "Industrial & Scientific",
  "Arts, Crafts & Sewing",
  "Musical Instruments",
  "Patio, Lawn & Garden",
  "Software",
  "Home Improvement",
  "Movies & TV",
  "Kindle Store",
  "CDs & Vinyl",
  "Digital Music",
  "Video Games",
  "Cell Phones & Accessories",
  "Clothing, Shoes & Jewelry",
  "Apps & Games",
  "Computers",
  "Garden & Outdoor",
  "Home Audio & Theater",
  "Kitchen & Dining",
  "Luggage & Travel Gear",
  "Magazine Subscriptions",
  "Miscellaneous",
  "Music",
  "Musical Instruments & DJ",
  "Office & School Supplies",
  "Outdoors",
  "Personal Computers",
  "Pet Food & Supplies",
  "Software & Services",
  "Sports",
  "Tools & Hardware",
  "Toys & Games & Baby",
  "Video",
  "Video & DVD",
  "Video Games & Consoles",
  "Watches",
  "Best Sellers",
  "Camera & Photo",
  "Car & Vehicle Electronics",
  "Cell Phones",
  "Computers & Accessories",
  "Electronics & Photo",
  "GPS & Navigation",
  "Headphones",
  "Hi-Fi & Home Audio",
  "Home Cinema, TV & Video",
  "Home Cinema, TV & Video Accessories",
  "Home Cinema, TV & Video Cables",
  "Home Cinema, TV & Video Remote Controls",
  "Kindle Store & Fire Tablets",
  "Kindle Store & Fire Tablets & E-Readers",
  "Kitchen & Home Appliances",
  "Mobile Phones & Communication",
  "PC & Video Games",
  "Portable Sound & Vision",
  "Sat Nav & Car Electronics",
  "Software & PC Games",
  "Stationery & Office Supplies",
  "Telephones, VOIP & Accessories",
  "Audio & Hi-Fi",
  "Camcorders",
  "Camera & Photo Accessories",
  "Digital Cameras",
  "Digital SLRs",
  "DVD & Blu-ray",
  "Headsets",
  "MP3 Players & Accessories",
  "Radio Communication",
  "Satellite Navigation",
  "Telephones & Accessories",
  "Television & Video",
  "Vehicles",
  "Accessories",
  "Car Parts",
  "Gifts & Merchandise",
  "Networking & Connectivity",
  "Peripherals & Accessories",
  "Printers & Ink",
  "Scanners",
  "Tablet Accessories",
  "Video Projectors",
  "Digital Music & Amazon Music Apps",
  "Kindle E-readers & Books",
  "Amazon Fire TV & Fire TV Accessories",
  "Amazon Launchpad",
  "Smart Home",
  "Software & Video Games",
];

export const productCategories = category.map((category, index) => ({
  id: index + 1,
  name: category,
}));
